"""
AI Document Generator

Generates professional business documents using Claude:
- AI Strategy Documents
- Governance Frameworks
- Implementation Roadmaps
- Executive Summaries
- Business Cases
"""

import json
import logging
from typing import Dict, List, Any, Optional
from dataclasses import dataclass
from datetime import datetime
from enum import Enum

from .claude_client import ClaudeClient, get_claude_client

logger = logging.getLogger(__name__)


class DocumentType(Enum):
    """Types of documents that can be generated"""
    EXECUTIVE_SUMMARY = "executive_summary"
    AI_STRATEGY = "ai_strategy"
    GOVERNANCE_FRAMEWORK = "governance_framework"
    ETHICS_POLICY = "ethics_policy"
    IMPLEMENTATION_ROADMAP = "implementation_roadmap"
    BUSINESS_CASE = "business_case"
    USE_CASE_PORTFOLIO = "use_case_portfolio"
    DATA_STRATEGY = "data_strategy"
    MLOPS_FRAMEWORK = "mlops_framework"
    CHANGE_MANAGEMENT_PLAN = "change_management_plan"


@dataclass
class GeneratedDocument:
    """Generated document with metadata"""
    doc_type: DocumentType
    title: str
    content: str
    organization_name: str
    generated_at: datetime
    word_count: int
    sections: List[str]
    based_on_assessment: bool

    def to_dict(self) -> Dict[str, Any]:
        return {
            "doc_type": self.doc_type.value,
            "title": self.title,
            "content": self.content,
            "organization_name": self.organization_name,
            "generated_at": self.generated_at.isoformat(),
            "word_count": self.word_count,
            "sections": self.sections,
            "based_on_assessment": self.based_on_assessment
        }

    def to_markdown(self) -> str:
        """Export as markdown"""
        return f"""# {self.title}

**Organization:** {self.organization_name}
**Generated:** {self.generated_at.strftime('%B %d, %Y')}
**Document Type:** {self.doc_type.value.replace('_', ' ').title()}

---

{self.content}

---
*Generated by AI Practice Platform - Patriot Tech Systems Consulting*
"""


class DocumentGenerator:
    """
    AI-powered document generator.

    Creates professional business documents based on
    assessment results and organizational context.
    """

    # Document templates with detailed prompts
    DOCUMENT_TEMPLATES = {
        DocumentType.EXECUTIVE_SUMMARY: {
            "title": "AI Readiness Executive Summary",
            "prompt": """Generate a 2-3 page Executive Summary of the AI Readiness Assessment.

Include these sections:
1. **Executive Overview** - One paragraph summary of findings
2. **Assessment Snapshot** - Key metrics in a clear format
3. **Maturity Assessment** - Current state analysis
4. **Key Findings** - Top 5 insights
5. **Critical Gaps** - Areas requiring immediate attention
6. **Recommended Actions** - Prioritized next steps (top 5)
7. **Investment Considerations** - High-level resource needs
8. **Next Steps** - Immediate actions for the next 30 days

Keep it concise, executive-friendly, and actionable."""
        },

        DocumentType.AI_STRATEGY: {
            "title": "Enterprise AI Strategy",
            "prompt": """Generate a comprehensive AI Strategy document.

Include these sections:
1. **Vision & Objectives**
   - AI vision statement
   - Strategic objectives (3-5)
   - Success metrics

2. **Current State Assessment**
   - Maturity level summary
   - Key capabilities
   - Critical gaps

3. **Strategic Pillars**
   - Data Foundation
   - Technology Platform
   - Talent & Skills
   - Governance & Ethics
   - Use Case Portfolio

4. **Target State** (12-24 months)
   - Desired maturity level
   - Key capabilities to build
   - Organizational changes

5. **Strategic Initiatives**
   - Initiative 1: [Based on top gap]
   - Initiative 2: [Based on second gap]
   - Initiative 3: [Based on opportunity]

6. **Investment & Resources**
   - Budget considerations
   - Team structure
   - Technology investments

7. **Risk Management**
   - Key risks
   - Mitigation strategies

8. **Governance Model**
   - Decision rights
   - Oversight structure

9. **Roadmap Summary**
   - Phase 1: Foundation (0-6 months)
   - Phase 2: Scale (6-12 months)
   - Phase 3: Optimize (12-24 months)

Make it strategic yet actionable, with specific recommendations based on their assessment."""
        },

        DocumentType.GOVERNANCE_FRAMEWORK: {
            "title": "AI Governance Framework",
            "prompt": """Generate a comprehensive AI Governance Framework.

Include these sections:
1. **Purpose & Scope**
   - Framework objectives
   - Applicability
   - Key definitions

2. **Governance Structure**
   - AI Steering Committee
   - AI Center of Excellence
   - Business Unit AI Leads
   - Roles and responsibilities matrix

3. **AI Lifecycle Governance**
   - Ideation & Use Case Approval
   - Development Standards
   - Testing & Validation
   - Deployment Approval
   - Monitoring & Maintenance
   - Retirement Process

4. **Risk Management**
   - AI Risk Categories
   - Risk Assessment Process
   - Risk Appetite Statement
   - Escalation Procedures

5. **Ethical AI Principles**
   - Fairness & Non-discrimination
   - Transparency & Explainability
   - Privacy & Data Protection
   - Accountability
   - Human Oversight

6. **Compliance Requirements**
   - Regulatory landscape
   - Internal policies
   - Audit requirements

7. **Model Governance**
   - Model inventory
   - Model validation
   - Model monitoring
   - Model documentation

8. **Third-Party AI**
   - Vendor assessment
   - Contract requirements
   - Ongoing monitoring

9. **Implementation Roadmap**
   - Quick wins
   - Medium-term actions
   - Long-term evolution

Include specific templates or checklists where helpful."""
        },

        DocumentType.ETHICS_POLICY: {
            "title": "AI Ethics Policy",
            "prompt": """Generate a comprehensive AI Ethics Policy.

Include these sections:
1. **Policy Statement**
   - Commitment to ethical AI
   - Scope and applicability

2. **Core Principles**
   - Human-Centered AI
   - Fairness & Equity
   - Transparency
   - Privacy & Security
   - Accountability
   - Reliability & Safety

3. **Principle Details** (for each principle)
   - Definition
   - Requirements
   - Examples
   - Prohibited practices

4. **Implementation Requirements**
   - Ethics review process
   - Documentation requirements
   - Training requirements

5. **Roles & Responsibilities**
   - AI Ethics Board
   - Project teams
   - Leadership

6. **Compliance & Enforcement**
   - Monitoring mechanisms
   - Violation reporting
   - Consequences

7. **Review & Updates**
   - Annual review process
   - Update triggers

Include practical guidance that can be immediately implemented."""
        },

        DocumentType.IMPLEMENTATION_ROADMAP: {
            "title": "AI Implementation Roadmap",
            "prompt": """Generate a detailed AI Implementation Roadmap.

Include these sections:
1. **Roadmap Overview**
   - Timeline summary
   - Key milestones
   - Success criteria

2. **Phase 1: Foundation (Months 1-6)**
   - Objectives
   - Key initiatives
   - Deliverables
   - Resource requirements
   - Dependencies
   - Risks

3. **Phase 2: Build (Months 7-12)**
   - Objectives
   - Key initiatives
   - Deliverables
   - Resource requirements
   - Dependencies
   - Risks

4. **Phase 3: Scale (Months 13-18)**
   - Objectives
   - Key initiatives
   - Deliverables
   - Resource requirements
   - Dependencies
   - Risks

5. **Phase 4: Optimize (Months 19-24)**
   - Objectives
   - Key initiatives
   - Deliverables
   - Resource requirements
   - Dependencies
   - Risks

6. **Resource Plan**
   - Team structure evolution
   - Budget by phase
   - Technology investments

7. **Governance Milestones**
   - Checkpoints
   - Decision gates
   - Reporting cadence

8. **Risk Management**
   - Key risks by phase
   - Mitigation strategies

9. **Success Metrics**
   - KPIs by phase
   - Measurement approach

Make timelines realistic based on their current maturity level."""
        },

        DocumentType.BUSINESS_CASE: {
            "title": "AI Investment Business Case",
            "prompt": """Generate a comprehensive AI Business Case.

Include these sections:
1. **Executive Summary**
   - Investment request
   - Expected returns
   - Recommendation

2. **Strategic Alignment**
   - Business objectives supported
   - Strategic fit

3. **Current State**
   - Assessment summary
   - Pain points
   - Opportunity cost of inaction

4. **Proposed Solution**
   - AI initiative description
   - Key components
   - Approach

5. **Benefits Analysis**
   - Quantitative benefits (cost savings, revenue, efficiency)
   - Qualitative benefits
   - Benefit realization timeline

6. **Investment Requirements**
   - Technology costs
   - Personnel costs
   - Training costs
   - Ongoing operational costs
   - Total Cost of Ownership (3-year)

7. **ROI Analysis**
   - NPV calculation
   - Payback period
   - IRR estimate
   - Sensitivity analysis

8. **Risk Assessment**
   - Implementation risks
   - Operational risks
   - Financial risks
   - Mitigation strategies

9. **Implementation Approach**
   - Phased approach
   - Key milestones
   - Resource plan

10. **Recommendation**
    - Go/No-Go recommendation
    - Conditions for success
    - Next steps

Include realistic financial estimates based on industry benchmarks."""
        },

        DocumentType.USE_CASE_PORTFOLIO: {
            "title": "AI Use Case Portfolio",
            "prompt": """Generate an AI Use Case Portfolio document.

Include these sections:
1. **Portfolio Overview**
   - Total use cases identified
   - Prioritization methodology
   - Portfolio summary

2. **Prioritization Matrix**
   - Value vs. Feasibility framework
   - Scoring criteria
   - Portfolio heat map description

3. **Tier 1: Quick Wins** (High Value, High Feasibility)
   For each use case:
   - Use case name & description
   - Business problem solved
   - AI/ML approach
   - Data requirements
   - Expected benefits
   - Implementation complexity
   - Timeline estimate
   - Resource needs

4. **Tier 2: Strategic Bets** (High Value, Lower Feasibility)
   [Same format as Tier 1]

5. **Tier 3: Foundation Builders** (Lower Value, High Feasibility)
   [Same format as Tier 1]

6. **Tier 4: Future Opportunities** (Requires More Maturity)
   [Brief descriptions]

7. **Dependencies & Sequencing**
   - Common data requirements
   - Technology prerequisites
   - Skill requirements
   - Recommended sequence

8. **Resource Requirements Summary**
   - Team needs
   - Technology needs
   - Data needs

9. **Recommended Roadmap**
   - Year 1 use cases
   - Year 2 use cases
   - Beyond

Generate 8-12 use cases relevant to their industry sector."""
        },

        DocumentType.DATA_STRATEGY: {
            "title": "AI Data Strategy",
            "prompt": """Generate an AI-focused Data Strategy document.

Include these sections:
1. **Vision & Objectives**
   - Data vision for AI
   - Strategic objectives

2. **Current State Assessment**
   - Data maturity summary
   - Key data assets
   - Critical gaps

3. **Data Architecture for AI**
   - Target architecture
   - Data lake/warehouse strategy
   - Real-time vs batch
   - Cloud strategy

4. **Data Governance for AI**
   - Governance framework
   - Data quality standards
   - Metadata management
   - Data lineage

5. **Data Quality Program**
   - Quality dimensions
   - Monitoring approach
   - Remediation process

6. **Data Access & Democratization**
   - Self-service analytics
   - Data catalog
   - Access controls

7. **AI-Ready Data**
   - Feature engineering
   - Data labeling
   - Training data management

8. **Privacy & Security**
   - Data classification
   - Privacy controls
   - Security measures

9. **Implementation Roadmap**
   - Phase 1: Foundation
   - Phase 2: Enablement
   - Phase 3: Optimization

10. **Success Metrics**
    - Data quality KPIs
    - Accessibility KPIs
    - AI enablement KPIs"""
        },

        DocumentType.MLOPS_FRAMEWORK: {
            "title": "MLOps Framework",
            "prompt": """Generate an MLOps Framework document.

Include these sections:
1. **MLOps Vision**
   - Objectives
   - Maturity target

2. **Current State**
   - Existing capabilities
   - Pain points

3. **MLOps Architecture**
   - Development environment
   - Training infrastructure
   - Model registry
   - Deployment pipeline
   - Monitoring stack

4. **ML Lifecycle Management**
   - Data preparation
   - Experimentation
   - Training & validation
   - Deployment
   - Monitoring & maintenance
   - Retraining triggers

5. **CI/CD for ML**
   - Code pipeline
   - Data pipeline
   - Model pipeline
   - Testing strategy

6. **Model Registry**
   - Version control
   - Metadata tracking
   - Lineage tracking
   - Approval workflow

7. **Monitoring & Observability**
   - Model performance
   - Data drift
   - Concept drift
   - Business metrics
   - Alerting

8. **Security & Compliance**
   - Access controls
   - Audit logging
   - Model explainability
   - Compliance checks

9. **Team & Skills**
   - Roles needed
   - Skills development

10. **Technology Stack Recommendations**
    - Platform options
    - Tool recommendations

11. **Implementation Roadmap**
    - Phase 1: Basic MLOps
    - Phase 2: Automated MLOps
    - Phase 3: Advanced MLOps"""
        },

        DocumentType.CHANGE_MANAGEMENT_PLAN: {
            "title": "AI Change Management Plan",
            "prompt": """Generate an AI Change Management Plan.

Include these sections:
1. **Change Overview**
   - AI transformation vision
   - Scope of change
   - Impact assessment

2. **Stakeholder Analysis**
   - Key stakeholder groups
   - Impact by group
   - Engagement strategy

3. **Communication Plan**
   - Key messages
   - Communication channels
   - Communication calendar
   - Feedback mechanisms

4. **Training & Enablement**
   - Training needs by role
   - Training programs
   - Learning paths
   - Success metrics

5. **Resistance Management**
   - Anticipated resistance
   - Root causes
   - Mitigation strategies
   - Escalation process

6. **Leadership Alignment**
   - Executive sponsorship
   - Leadership behaviors
   - Role modeling

7. **Organizational Readiness**
   - Readiness assessment
   - Readiness activities
   - Go-live criteria

8. **Sustainment**
   - Reinforcement mechanisms
   - Recognition programs
   - Continuous improvement

9. **Metrics & Monitoring**
   - Adoption metrics
   - Engagement metrics
   - Proficiency metrics

10. **Implementation Timeline**
    - Pre-launch activities
    - Launch activities
    - Post-launch activities"""
        }
    }

    def __init__(self, claude_client: Optional[ClaudeClient] = None):
        """Initialize document generator"""
        self.claude = claude_client or get_claude_client()

    def generate(
        self,
        doc_type: DocumentType,
        organization_name: str,
        assessment_result: Optional[Dict] = None,
        sector: str = "general",
        custom_requirements: Optional[str] = None
    ) -> GeneratedDocument:
        """
        Generate a document.

        Args:
            doc_type: Type of document to generate
            organization_name: Organization name
            assessment_result: Optional assessment results
            sector: Industry sector
            custom_requirements: Additional requirements

        Returns:
            GeneratedDocument
        """
        template = self.DOCUMENT_TEMPLATES.get(doc_type)
        if not template:
            raise ValueError(f"Unknown document type: {doc_type}")

        # Build context
        context = {
            "organization_name": organization_name,
            "sector": sector,
            "document_type": doc_type.value
        }

        if assessment_result:
            context["assessment"] = {
                "overall_score": assessment_result.get("overall_score"),
                "maturity_level": assessment_result.get("maturity_level"),
                "grade": assessment_result.get("grade"),
                "dimension_scores": assessment_result.get("dimension_scores"),
                "top_strengths": assessment_result.get("top_strengths", []),
                "top_improvements": assessment_result.get("top_improvements", []),
                "recommendations": assessment_result.get("recommendations", [])
            }

        # Build prompt
        prompt = template["prompt"]
        if custom_requirements:
            prompt += f"\n\nAdditional Requirements:\n{custom_requirements}"

        prompt += f"\n\nOrganization: {organization_name}"
        prompt += f"\nIndustry Sector: {sector}"

        if assessment_result:
            prompt += f"\nCurrent Maturity: {assessment_result.get('maturity_level', 'Unknown')}"
            prompt += f"\nOverall Score: {assessment_result.get('overall_score', 'N/A')}/100"

        # Generate document
        logger.info(f"Generating {doc_type.value} for {organization_name}")
        content = self.claude.generate_document(doc_type.value, context, prompt)

        # Parse sections from content
        sections = self._extract_sections(content)

        return GeneratedDocument(
            doc_type=doc_type,
            title=f"{template['title']} - {organization_name}",
            content=content,
            organization_name=organization_name,
            generated_at=datetime.now(),
            word_count=len(content.split()),
            sections=sections,
            based_on_assessment=assessment_result is not None
        )

    def _extract_sections(self, content: str) -> List[str]:
        """Extract section headers from content"""
        sections = []
        for line in content.split('\n'):
            line = line.strip()
            if line.startswith('# '):
                sections.append(line[2:])
            elif line.startswith('## '):
                sections.append(line[3:])
            elif line.startswith('**') and line.endswith('**'):
                sections.append(line[2:-2])
        return sections[:15]  # Limit to first 15 sections

    def get_available_documents(self) -> List[Dict[str, str]]:
        """Get list of available document types"""
        return [
            {
                "type": doc_type.value,
                "title": template["title"],
                "description": template["prompt"].split('\n')[0]
            }
            for doc_type, template in self.DOCUMENT_TEMPLATES.items()
        ]

    def generate_all_core_documents(
        self,
        organization_name: str,
        assessment_result: Dict,
        sector: str = "general"
    ) -> List[GeneratedDocument]:
        """
        Generate all core documents for a complete package.

        Args:
            organization_name: Organization name
            assessment_result: Assessment results
            sector: Industry sector

        Returns:
            List of generated documents
        """
        core_types = [
            DocumentType.EXECUTIVE_SUMMARY,
            DocumentType.AI_STRATEGY,
            DocumentType.GOVERNANCE_FRAMEWORK,
            DocumentType.IMPLEMENTATION_ROADMAP
        ]

        documents = []
        for doc_type in core_types:
            doc = self.generate(
                doc_type=doc_type,
                organization_name=organization_name,
                assessment_result=assessment_result,
                sector=sector
            )
            documents.append(doc)

        return documents


# Singleton instance
_generator: Optional[DocumentGenerator] = None


def get_document_generator() -> DocumentGenerator:
    """Get or create singleton document generator"""
    global _generator
    if _generator is None:
        _generator = DocumentGenerator()
    return _generator
